services:
  - type: web
    name: telegram-gif-bot
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install --no-cache-dir -r requirements.txt
    startCommand: python3 render_bot.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
